Fix testsuite: conflict with a test(..) template from Boost.
Error log:
/home/lrineau/CGAL/boost/1.44-beta1/include/boost/type_traits/has_new_operator.hpp: In function 'int main()':
/home/lrineau/CGAL/boost/1.44-beta1/include/boost/type_traits/has_new_operator.hpp:24: error: 'template<class U, U x> struct boost::detail::test' is not a function,
/home/lrineau/CGAL/CGAL-3.7-I-157/cmake/platforms/x86-64_Linux-2.6_g++-4.4.4_F13/test/Number_types/to_interval_test.cpp:30: error:   conflict with 'template<class NT> void test(const NT&)'
/home/lrineau/CGAL/CGAL-3.7-I-157/cmake/platforms/x86-64_Linux-2.6_g++-4.4.4_F13/test/Number_types/to_interval_test.cpp:73: error:   in call to 'test'