Add explicit casts
This seems required. At least the Intel Compiler version 12 gives a set of errors
(not even warnings!). Here is one of them:

/home/lrineau/CGAL/CGAL-4.0-Ic-248/include/CGAL/Periodic_3_triangulation_ds_cell_base_3.h:192:29: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list
    unsigned int off0[3] = {(o0>>2)&1,(o0>>1)&1,(o0&1)};
                            ^~~~~~~~~
/home/lrineau/CGAL/CGAL-4.0-Ic-248/include/CGAL/Periodic_3_triangulation_ds_cell_base_3.h:192:29: note: override this message by inserting an explicit cast
    unsigned int off0[3] = {(o0>>2)&1,(o0>>1)&1,(o0&1)};
                            ^~~~~~~~~
                            static_ca)t<unsigned int>(