Use -DQT_NO_KEYWORDS
... to avoid conflicts with Boost headers, such as:
```
boost/multi_index/hashed_index.hpp(1254) : error C3083: 'Q_FOREACH': the symbol to the left of a '::' must be a type
```