rebase: fix named parameter compile error
error c2953: class template has already been defined
after rebase: property_map_selector/get_property_map/get_const_property_map
has already been defined in CGAL/boost/graph/named_function_params.h