QOpenGLShaderProgram::create was introduced in Qt-5.3
With Qt-5.2:

    error: 'class QOpenGLShaderProgram' has no member named 'create'

Anyway, that call is useless.