Fix a compilation error
The error, on clang, is:

include/CGAL/Algebraic_structure_traits.h:362:39: error: declaration of 'Type_' shadows template parameter
            typedef typename CT::Type Type_;

The bug was introduced by the following commit:
  | commit 02e17dfdf020d2ba1fa61e1c0bd8214a89841a3c
  | Author: Michael Hemmer <mhsaar@gmail.com>
  | Date:   Mon Sep 2 18:28:55 2013 +0300
  |
  |     fixed boost::is_same<Type,Type>
  |
  |     minor fix for master