Use a fully-qualified name for ::test, because otherwise there is a conflict with something from Boost:
/home/lrineau/CGAL/boost/1.44-beta1/include/boost/type_traits/has_new_operator.hpp: In function 'int main()':
/home/lrineau/CGAL/boost/1.44-beta1/include/boost/type_traits/has_new_operator.hpp:24: error: 'template<class U, U x> struct boost::detail::test' is not a function,
/home/lrineau/CGAL/CGAL-3.7-I-135/cmake/platforms/x86-64_Linux-2.6_g++-4.4.4_F13-MATCHING-BUG-6/test/Min_sphere_of_spheres_d/interface_check.cpp:147: error:   conflict with 'template<int D, class FT, class Sqrt, class Alg> void test(int, const FT&)'
/home/lrineau/CGAL/CGAL-3.7-I-135/cmake/platforms/x86-64_Linux-2.6_g++-4.4.4_F13-MATCHING-BUG-6/test/Min_sphere_of_spheres_d/interface_check.cpp:210: error:   in call to 'test'