Fix compilation error with llvm-gcc-4.2
The error was:
/usr/local/include/boost/type_traits/has_new_operator.hpp: In function 'bool test_ray(Arrangement_2&, Face_handle)':
/usr/local/include/boost/type_traits/has_new_operator.hpp:24: error: 'template<class U, U x> struct boost::detail::test' is not a function,
CGAL-4.5-Ic-86/cmake/platforms/x86-64_Darwin-13.0_Apple-llvm-gcc-4.2_Release/test/Arrangement_on_surface_2/test_unbounded_removal.cpp:24: error:   conflict with 'bool test(const Arrangement_2&)'
CGAL-4.5-Ic-86/cmake/platforms/x86-64_Darwin-13.0_Apple-llvm-gcc-4.2_Release/test/Arrangement_on_surface_2/test_unbounded_removal.cpp:55: error:   in call to 'test'

I do not understand how `boost::detail::test` was introduced in the
matching set of functions. The `boost::detail` namespace is not supposed
to be involved.