Workaround a conflict between Boost>=1.48 and Qt
Just changing the order of includes works around the issue.

The error was:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/cmake/platforms/x86-64_Linux-2.6_llvm-clang-with-g++-4.6.2_F16/test/Surface_mesher_Demo/volume.cpp:10:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/cmake/platforms/x86-64_Linux-2.6_llvm-clang-with-g++-4.6.2_F16/test/Surface_mesher_Demo/./volume.h:61:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/include/CGAL/Implicit_surface_3.h:23:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/include/CGAL/make_surface_mesh.h:23:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/include/CGAL/Surface_mesher_generator.h:24:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/include/CGAL/Surface_mesher/Surface_mesher.h:33:
In file included from /home/lrineau/CGAL/CGAL-4.1-Ic-78/include/CGAL/Double_map.h:40:
In file included from /home/lrineau/CGAL/boost/boost-release-branch/boost/bimap.hpp:13:
In file included from /home/lrineau/CGAL/boost/boost-release-branch/boost/bimap/bimap.hpp:61:
In file included from /home/lrineau/CGAL/boost/boost-release-branch/boost/bimap/detail/bimap_core.hpp:43:
In file included from /home/lrineau/CGAL/boost/boost-release-branch/boost/bimap/detail/manage_bimap_key.hpp:26:
In file included from /home/lrineau/CGAL/boost/boost-release-branch/boost/bimap/set_of.hpp:37:
/home/lrineau/CGAL/boost/boost-release-branch/boost/multi_index/ordered_index.hpp:1399:10: error: no member named 'Q_FOREACH' in namespace 'boost'
  boost::foreach::tag)
  ~~~~~~~^
/usr/include/QtCore/qglobal.h:2418:21: note: expanded from macro 'foreach'
#    define foreach Q_FOREACH
                    ^
5 warnings and 1 error generated.