Recorded merge of revisions 51561,51678,51694,51699,51702,51714,51738,51758,51769,51771,51778,51787,51814,51831,51868,51889,51895,51901-51902,51931-51932,51936-51937,51939,51948,51953-51954,51957,51960,51999,52026,52075,52079,52094-52096,52101-52105,52110-52111,52115,52141-52143,52150-52151,52197,52582,52584,52618,52733,52843,53002,53053,53152,53292-53294 via svnmerge from svn+ssh://lrineau@scm.gforge.inria.fr/svn/cgal/branches/CGAL-3.5-branch
Personal note: Actually all merges were already done in the trunk manually
by authors, as far as I have seen. I have ignored several conflicts in
Mesh_3 and packages from Laurent Saboret, because I know the authors of
these packages already manage patchs to 3.5 and trunk manually. All the
changes here seem to be fixes to package descriptions (change -08 to -09).

........
  r51561 | stayeb | 2009-08-27 17:41:39 +0200 (Thu, 27 Aug 2009) | 8 lines
  
  Merge r51076
  From trunk/Mesh_3/include/CGAL/Labeled_image_mesh_domain_3.h to branches/CGAL-3.5-branch/Mesh_3/include/CGAL/Labeled_image_mesh_domain_3.h
  
  r51076 | stayeb | 2009-08-05 17:40:23 +0200 (Wed, 05 Aug 2009) | 3 lines
  * Fix bug with image bounding box computation
  * Add internal(undocumented) usefull genericity:
    + add Wrapper template parameter (with default value) in Labeled_Image_mesh_domain_3
........
  r51678 | lsaboret | 2009-09-02 14:16:10 +0200 (Wed, 02 Sep 2009) | 6 lines
  
  svn merge bug fix from trunk to CGAL-3.5-branch:
  
  r51677 | lsaboret
  Port to Windows 64
........
  r51694 | stayeb | 2009-09-02 16:30:21 +0200 (Wed, 02 Sep 2009) | 1 line
  
  add multilabel_mesh_small picture.
........
  r51699 | lrineau | 2009-09-02 16:42:46 +0200 (Wed, 02 Sep 2009) | 35 lines
  
  Merge the following revision from trunk into the 3.5 branch:
    | ------------------------------------------------------------------------
    | r51688 | lrineau | 2009-09-02 16:07:12 +0200 (Wed, 02 Sep 2009) | 2 lines
    | 
    | A new solution for the "how_to_cite stuff"
    | 
    | ------------------------------------------------------------------------
    | r51689 | lrineau | 2009-09-02 16:08:14 +0200 (Wed, 02 Sep 2009) | 2 lines
    | 
    | Remove the last non-constant part of the script makebiblio !!! :-)
    | 
    | ------------------------------------------------------------------------
    | r51679 | lrineau | 2009-09-02 14:48:37 +0200 (Wed, 02 Sep 2009) | 4 lines
    | 
    | Fix after Monique's suggestion... Just kidding! :-)
    | 
    | Actually, we do not want CGAL Editorial Board to be abbrev. to "C.E.Board".
    | 
    | ------------------------------------------------------------------------
    | r51680 | lrineau | 2009-09-02 14:52:09 +0200 (Wed, 02 Sep 2009) | 2 lines
    | 
    | Protect Minkowski and Boolean with {}.
    | 
    | ------------------------------------------------------------------------
    | r51692 | lrineau | 2009-09-02 16:15:22 +0200 (Wed, 02 Sep 2009) | 6 lines
    | 
    | Fixes:
    |  - Remove the links "BACK TO INDEX" that were auto-generated by
    |    bibtex2html
    |  - Remove several "and and".
    |  - Replace the labels: "08" -> "09".
    | 
    | ------------------------------------------------------------------------
........
  r51702 | yvinec | 2009-09-02 16:51:07 +0200 (Wed, 02 Sep 2009) | 3 lines
  
  fixed PkgDescription.tex
........
  r51714 | spion | 2009-09-02 18:46:41 +0200 (Wed, 02 Sep 2009) | 4 lines
  
  Backport revision 51047.
  
    Replace wrong use of $$ by \ccc{}.
........
  r51738 | lrineau | 2009-09-03 09:24:23 +0200 (Thu, 03 Sep 2009) | 2 lines
  
  Import revision 51737 from trunk: fix the how_to_cite_cgal.html file
........
  r51758 | lrineau | 2009-09-03 12:14:14 +0200 (Thu, 03 Sep 2009) | 1 line
  
  Fix all \ccPkgHowToCiteCgal at once to turn 08 into 09
........
  r51769 | lrineau | 2009-09-03 14:03:23 +0200 (Thu, 03 Sep 2009) | 14 lines
  
  Merge from trunk:
     | ------------------------------------------------------------------------
     | r51754 | teillaud | 2009-09-03 11:45:05 +0200 (Thu, 03 Sep 2009) | 2 lines
     | 
     | added missing file, needed by makebiblio
     | 
     | ------------------------------------------------------------------------
     | r51755 | teillaud | 2009-09-03 11:48:45 +0200 (Thu, 03 Sep 2009) | 2 lines
     | 
     | layout file for makebiblio (use of ccs)
     | 
     | ------------------------------------------------------------------------
........
  r51771 | lrineau | 2009-09-03 14:20:50 +0200 (Thu, 03 Sep 2009) | 10 lines
  
  Merge from trunk:
    | ------------------------------------------------------------------------
    | r51770 | teillaud | 2009-09-03 14:14:17 +0200 (Thu, 03 Sep 2009) | 3 lines
    | 
    | a few buggy labels fixed
    | obviously, it was not a good idea to write them using the keyboard alone, not even the mouse... :(
    | 
    | ------------------------------------------------------------------------
........
  r51778 | lrineau | 2009-09-03 16:38:42 +0200 (Thu, 03 Sep 2009) | 3 lines
  
  Fill the file global_dont_submit, so that one can simplify the script that
  creates releases.
........
  r51787 | lsaboret | 2009-09-03 18:00:04 +0200 (Thu, 03 Sep 2009) | 15 lines
  
  Merge bug fixes from trunk to CGAL-3.5-branch:
  
  r51785 | lsaboret
  * Fixed images width (as requested by LR):
  set max-width instead of width in HTML.
  * Also set width=1.0 for most images in PDF (prettier).
  
  r51749 | lsaboret
  Fixed warning with boost >= 10.38 in Point_set_processing_3.
  
  r51683 | lsaboret
  Fixed compilation error due to the global change "CGALi" -> "internal" in trunk
  (this revision is merged into CGAL-3.5-branch by safety)
........
  r51814 | teillaud | 2009-09-04 10:16:38 +0200 (Fri, 04 Sep 2009) | 2 lines
  
  files generated after yesterday's fixes on manual-3.5.bib
........
  r51831 | lsaboret | 2009-09-04 13:38:11 +0200 (Fri, 04 Sep 2009) | 6 lines
  
  Merge bug fix from trunk to CGAL-3.5-branch:
  
  r51830 | lsaboret
  Fixed compilation error introduced in r51749
........
  r51868 | lrineau | 2009-09-07 17:01:48 +0200 (Mon, 07 Sep 2009) | 2 lines
  
  Fix the non-filtering of BBox_3-Segment_3 intersection.
........
  r51889 | palliez | 2009-09-10 17:02:29 +0200 (Thu, 10 Sep 2009) | 1 line
  
  fix pca bug
........
  r51895 | lsaboret | 2009-09-10 18:34:35 +0200 (Thu, 10 Sep 2009) | 66 lines
  
  Merge bug fixes from trunk to CGAL-3.5-branch:
  
  r51894 | lsaboret
  Added traces
  
  r51893 | lsaboret
  Fixed bug introduced in r51683:
  (Windows) developers compiling Surface_reconstruction_points_3 with CGAL 3.5 beta 1 need to compile with Surface_mesher package from svn in order to get r51028 bug fix (orientation of reconstructed meshes).
  
  r51887 | lsaboret
  Fixed bug in test suite:
  * The bug occured (sometimes) in test suite when calling
  > APSS_reconstruction_test data/robocat_deci.off
  => assertion failure "CGAL::Polyhedron_incremental_builder_3<HDS>::
  lookup_halfedge(): input error: facet 1462 shares a halfedge from vertex 95 to vertex 808 with facet 1312."
  in output_surface_facets_to_polyhedron().
  This means that the reconstructed surface is not manifold.
  * The reason seems that (on this example) APSS implicit function is not smooth enough for make_surface_mesh().
  * The fix was to set APSS smoothness factor to 6 (default is 2).
  
  r51886 | lsaboret
  Partial fix of assertion failure "(x,y,z) is already inserted on surface" in make_surface_mesh():
  * The bug could be reproduce by:
  > poisson_reconstruction Compressor_top_clean_65kpoints.pwn out.off -sm_distance 0.75
  or
  > APSS_reconstruction robocat_deci.off out.off -smooth 6
  (try several times)
  * The fix is to set Implicit_surface_3's dichotomy error to make_surface_mesh's approximation distance/1000 (instead of /10). This makes make_surface_mesh() behavior more reproductible.
  * My guess is that in both implicit functions are not smooth, and that make_surface_mesh's parameters must be tuned to make them appear smooth to the algorithm.
  
  r51884 | lsaboret
  Temporary traces: turn on CGAL assertions
  
  r51883 | lsaboret
  Temporary traces: turn on CGAL assertions
  
  r51873 | lsaboret
  Fixed bug in make_surface_mesh(implicit surface, sphere, Manifold_tag) when the implicit surface crosses the sphere:
  * The bug could be reproduced on Linux/g++ 4.3.1 by:
  > poisson_reconstruction Compressor_top_clean_30kpoints.pwn Compressor-poisson.off
  or
  > APSS_reconstruction robocat_deci.off robocat_deci-apss.off
  => infinite loop that crashes when the process max memory is reached, or
     assertion failure "(x,y,z) is already inserted on surface", or
     assertion failure "A facet is not in conflict with its refinement point"
  * The fix was to use Manifold_with_boundary_tag.
  
  r51871 | palliez
  update barycentric coordinates - thanks Andreas.
  
  r51869 | lsaboret
  Fixed assertion failure "tester(d)" in Triangulation_3::find_conflicts() when running the Delaunay refinement:
  * To reproduce the bug:
  > poisson_reconstruction data/sphere926.pwn sphere926-poisson.off
  (try several times)
  * The fix is:
  - implement Robust_circumcenter_filtered_traits_3::compute_squared_radius_3_object()
  - compare denominator with 1E-13 (instead of 1E-14) to switch to exact arithmetic
  
  r51865 | lsaboret
  Fixed infinite loop in Min_sphere_d:
  * On Linux/g++, the bug could be reproduced by:
  > poisson_reconstruction data/sphere926.pwn sphere926-poisson.off
  * The fix was do use Min_sphere_of_spheres_d instead of Min_sphere_d
........
  r51901 | palliez | 2009-09-11 09:13:41 +0200 (Fri, 11 Sep 2009) | 1 line
  
  PCA: undo recent change - there was no bug
........
  r51902 | lrineau | 2009-09-11 10:44:55 +0200 (Fri, 11 Sep 2009) | 16 lines
  
  Remove mention to piecewise smooth surfaces. The following revision forgot
  to remove those two paragraphs:
    | ------------------------------------------------------------------------
    | r46327 | lrineau | 2008-10-17 14:35:23 +0200 (Fri, 17 Oct 2008) | 3 lines
    | Changed paths:
    |    M /trunk/Surface_mesher/doc_tex/Surface_mesher/main.tex
    |    M /trunk/Surface_mesher/doc_tex/Surface_mesher_ref/SurfaceMeshFacetsCriteria_3.tex
    |    M /trunk/Surface_mesher/doc_tex/Surface_mesher_ref/Surface_mesh_complex_2_in_triangulation_3.tex
    |    M /trunk/Surface_mesher/doc_tex/Surface_mesher_ref/intro.tex
    |    M /trunk/Surface_mesher/doc_tex/Surface_mesher_ref/main.tex
    | 
    | Update documentation for CGAL-3.4: remove any occurrence of "polyhedral
    | [surfaces]" and "piecewise [smooth surfaces]"
    | 
    | ------------------------------------------------------------------------
........
  r51931 | stayeb | 2009-09-14 15:22:12 +0200 (Mon, 14 Sep 2009) | 1 line
  
  Fix bbox_3_segment_3 intersection for filtered kernels.
........
  r51932 | lrineau | 2009-09-14 15:32:24 +0200 (Mon, 14 Sep 2009) | 3 lines
  
  Fix predicates of <CGAL/AABB_intersection.h>, so that they are correctly
  filtered when called from the global function template CGAL::do_intersect
........
  r51936 | stayeb | 2009-09-14 19:37:18 +0200 (Mon, 14 Sep 2009) | 2 lines
  
  * Fix ray_bbox & line_bbox do_intersect predicates for filtered kernels
  * add a small test for do_intersect(seg/ray/line, bbox) queries
........
  r51937 | stayeb | 2009-09-14 19:52:01 +0200 (Mon, 14 Sep 2009) | 1 line
  
  Fix polyhedral oracle issue: switch to exact intersection computation.
........
  r51939 | stayeb | 2009-09-15 10:56:32 +0200 (Tue, 15 Sep 2009) | 1 line
  
  Fix minor bug in aabb_do_intersect_test.cpp
........
  r51948 | spion | 2009-09-15 19:09:03 +0200 (Tue, 15 Sep 2009) | 5 lines
  
  Rename following the converging convention to prevent future incompatibility :
  - Vertex_container -> Vertex_range
  - Face_container   -> Face_range
  - Cell_container   -> Cell_range
........
  r51953 | stayeb | 2009-09-16 13:17:12 +0200 (Wed, 16 Sep 2009) | 1 line
  
  Fix AABB_tree missing default ctor.
........
  r51954 | stayeb | 2009-09-16 14:40:50 +0200 (Wed, 16 Sep 2009) | 6 lines
  
  Merge [r51090]
  From trunk/Mesh_3 to branches/CGAL-3.5-branch/Mesh_3.
  
  r51090 | stayeb 
  * Labels are now ordered according to their natural order (instead of randomly) in medit output.
........
  r51957 | stayeb | 2009-09-17 10:20:36 +0200 (Thu, 17 Sep 2009) | 1 line
  
  cleanup example folder.
........
  r51960 | stayeb | 2009-09-17 13:10:50 +0200 (Thu, 17 Sep 2009) | 1 line
  
  Remove wrong using namespace statement.
........
  r51999 | lsaboret | 2009-09-22 10:27:10 +0200 (Tue, 22 Sep 2009) | 1 line
  
  Removed debugging traces
........
  r52026 | lrineau | 2009-09-28 14:18:10 +0200 (Mon, 28 Sep 2009) | 2 lines
  
  Add a minor changelog from CGAL-3.5-beta1.
........
  r52075 | lrineau | 2009-09-30 17:24:08 +0200 (Wed, 30 Sep 2009) | 2 lines
  
  Fix the display of the manual testsuite: pdflatex before bibtex and so on.
........
  r52079 | lrineau | 2009-10-01 00:21:47 +0200 (Thu, 01 Oct 2009) | 1 line
  
  Fix links to Boost property maps documentation.
........
  r52094 | lrineau | 2009-10-01 17:43:44 +0200 (Thu, 01 Oct 2009) | 2 lines
  
  Fix the background of dev manual
........
  r52095 | lrineau | 2009-10-01 18:06:36 +0200 (Thu, 01 Oct 2009) | 4 lines
  
  
  #include <cstdio> is needed, with recent g++ compilers, to find the BUFSIZ
  macro.
........
  r52096 | lrineau | 2009-10-01 18:07:03 +0200 (Thu, 01 Oct 2009) | 3 lines
  
  
  Detect images that are linked with background=...
........
  r52101 | lrineau | 2009-10-01 18:32:46 +0200 (Thu, 01 Oct 2009) | 2 lines
  
  Fix the bibtex entry of Mesh_3: incorrect title
........
  r52102 | lrineau | 2009-10-01 18:34:59 +0200 (Thu, 01 Oct 2009) | 2 lines
  
  Real fix of the bib entry of Mesh_3!
........
  r52103 | lrineau | 2009-10-01 18:36:08 +0200 (Thu, 01 Oct 2009) | 1 line
  
  Commit of changes to how_to_cite in the manual tools... (fix the mesh_3 entry)
........
  r52104 | lrineau | 2009-10-01 18:41:39 +0200 (Thu, 01 Oct 2009) | 2 lines
  
  Error checking
........
  r52105 | lrineau | 2009-10-01 18:49:38 +0200 (Thu, 01 Oct 2009) | 2 lines
  
  Add README files about the generation of the how_to_cite_cgal stuff.
........
  r52110 | lrineau | 2009-10-02 10:55:03 +0200 (Fri, 02 Oct 2009) | 2 lines
  
  Fix HTML errors in the manual testsuite results pages.
........
  r52111 | lrineau | 2009-10-02 11:11:46 +0200 (Fri, 02 Oct 2009) | 3 lines
  
  Add the link to the HTML validator. The manual testsuite pages validate,
  now.
........
  r52115 | lrineau | 2009-10-02 16:47:37 +0200 (Fri, 02 Oct 2009) | 2 lines
  
  Minor fix of the output of the manual testsuite.
........
  r52141 | lrineau | 2009-10-05 14:28:24 +0200 (Mon, 05 Oct 2009) | 2 lines
  
  Patch from Olivier Devillers: add a check in is_valid.
........
  r52142 | lrineau | 2009-10-05 14:33:01 +0200 (Mon, 05 Oct 2009) | 2 lines
  
  CGAL-3.5 published. Let's target 3.5.1, now.
........
  r52143 | lrineau | 2009-10-05 14:39:18 +0200 (Mon, 05 Oct 2009) | 2 lines
  
  Fix a link in the bibtex file.
........
  r52150 | lrineau | 2009-10-05 19:01:43 +0200 (Mon, 05 Oct 2009) | 3 lines
  
  Update the LaTeX label for "3D Periodic Triangulations" (the previous one
  was a copy-paste from TDS_3).
........
  r52151 | reichel | 2009-10-05 22:47:27 +0200 (Mon, 05 Oct 2009) | 2 lines
  
  update Debian stuff for 3.5-1
........
  r52197 | lrineau | 2009-10-07 21:57:10 +0200 (Wed, 07 Oct 2009) | 2 lines
  
  Boost 1.33.1 *or higher* is needed.
........
  r52582 | mcaroli | 2009-10-16 10:19:24 +0200 (Fri, 16 Oct 2009) | 3 lines
  
  bugfix I/O operator
  merge of revision 52311 from trunk
........
  r52584 | mcaroli | 2009-10-16 10:45:08 +0200 (Fri, 16 Oct 2009) | 3 lines
  
  minor improvements in the reference documentation.
  this is a merge from the trunk
........
  r52618 | mcaroli | 2009-10-19 17:50:53 +0200 (Mon, 19 Oct 2009) | 2 lines
  
  move the new check in is_valid to the right place (cf. r52141)
........
  r52733 | mcaroli | 2009-10-26 10:15:53 +0100 (Mon, 26 Oct 2009) | 11 lines
  
  Merge revisions r52701 and r52704 from trunk:
  | ------------------------------------------------------------------------
  | r52701 | mcaroli | 2009-10-23 11:15:57 +0200 (Fri, 23 Oct 2009) | 2 lines
  |
  | add the domain to the basic example
  | ------------------------------------------------------------------------
  | r52704 | mcaroli | 2009-10-23 11:56:56 +0200 (Fri, 23 Oct 2009) | 2 lines
  |
  | add a phrase that precises that input points have to lie inside the cube
  | ------------------------------------------------------------------------
........
  r52843 | lrineau | 2009-11-02 14:28:09 +0100 (Mon, 02 Nov 2009) | 2 lines
  
  g++-4.4 is supported as well.
........
  r53002 | mcaroli | 2009-11-12 18:05:01 +0100 (Thu, 12 Nov 2009) | 3 lines
  
  improved doc of periodic_point(v) and periodic_point(v,i)
  this is a merge from the trunk, revision 53001
........
  r53053 | stayeb | 2009-11-16 13:56:49 +0100 (Mon, 16 Nov 2009) | 5 lines
  
  Merge r53048 from trunk
  
  r53048 | stayeb
  Fix syntax error.
........
  r53152 | stayeb | 2009-11-24 13:43:03 +0100 (Tue, 24 Nov 2009) | 1 line
  
  Fix bug (typo) in polyhedral domain initialization.
........
  r53292 | lrineau | 2009-12-04 16:00:00 +0100 (Fri, 04 Dec 2009) | 1 line
  
  commit revision 53291 from trunk to branch 3.5
........
  r53293 | lrineau | 2009-12-04 16:01:30 +0100 (Fri, 04 Dec 2009) | 1 line
  
  commit revision 53289\ from trunk to branch 3.5
........
  r53294 | lrineau | 2009-12-04 16:02:06 +0100 (Fri, 04 Dec 2009) | 1 line
  
  commit revision 53288 from trunk to branch 3.5
........