Remove /Zm flags from Windows testsuites
The flag /Zm can cause the error C1060. It may only be useful if one uses
precompiled headers.

See:
http://msdn.microsoft.com/en-us/library/bdscwf1c%28v=vs.90%29.aspx