Use a full-qualified name, because a of conflict with something from Boost.
Old error log:
/home/lrineau/CGAL/boost/1.44-beta1/include/boost/type_traits/has_new_operator.hpp: In function 'bool test_one_file(std::ifstream&)':
/home/lrineau/CGAL/boost/1.44-beta1/include/boost/type_traits/has_new_operator.hpp:24: error: 'template<class U, U x> struct boost::detail::test' is not a function,
/home/lrineau/CGAL/CGAL-3.7-I-135/cmake/platforms/x86-64_Linux-2.6_g++-4.4.4_F13-MATCHING-BUG-6/test/Boolean_set_operations_2/test_bop.cpp:137: error:   conflict with 'template<class Polygon1, class Polygon2> bool test(std::istream&, const Polygon1&, const Polygon2&)'
/home/lrineau/CGAL/CGAL-3.7-I-135/cmake/platforms/x86-64_Linux-2.6_g++-4.4.4_F13-MATCHING-BUG-6/test/Boolean_set_operations_2/test_bop.cpp:386: error:   in call to 'test'